#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - find-latest-version                  Copyright(c) 2020 cPanel, L.L.C.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package ea_libzip::find_latest_version;

use strict;
use warnings;

use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

ea4_tool::util::find_latest_version( \&_get_required, \&_add_sum ) if !caller();

###############
#### helpers ##
###############

sub _get_required {
    my ($http) = @_;

    my ( $version, $url, $name );

    #my $res = $http->get("https://api.github.com/repos/unicode-org/icu/tags");

    my $tag_refs = [ { name => "release-67-1" } ];    # ea4_tool::util::json2ref( $res->{content} );
    my $tag;

    # "release-66-1"

    foreach my $tag_ref ( @{$tag_refs} ) {
        my $tname = $tag_ref->{'name'};
        next if ( $tname !~ m/^release-\d+-\d+$/ );

        if ( !defined $tag ) {
            $tag = $tag_ref;
            next;
        }

        if ( $tag_ref->{name} gt $tag->{name} ) {
            $tag = $tag_ref;
            next;
        }
    }

    die "Cannot find latest version" if !defined $tag;

    $name = $tag->{name};
    if ( $name =~ m/^release-(\d+)-(\d+)$/ ) {
        $version = "$1.$2";
    }
    else {
        die "That should not have happened";
    }

    $name .= ".tar.gz";
    $name =~ s{(.*)\-}{$1\.}g;

    my $version_in_name = $version;
    $version_in_name =~ s/\./\-/g;

    $url = "https://github.com/unicode-org/icu/archive/release-$version_in_name.tar.gz";
    return ( $version, $url, $name );
}

sub _add_sum {
    my ( $http, $hr ) = @_;

    # I could not find a way to get the sum

    return;
}

__END__

=encoding utf-8

=head1 README

This is a Github project.  The latest version is listed as a tag in the project.

